name: CI

on:
  push:
    branches: [master, v0.*]
  pull_request:
    branches: master
  schedule:
    - cron:  '0 6 * * 1,4' # Each Monday and Thursday at 06:00 UTC
  workflow_dispatch:

env:
  NB_KERNEL: python
  MPLBACKEND: Agg
  WATEX_DATA: ${{ github.workspace }}/watex-data

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11"]
        install: [full]
        deps: [latest]

        include:
          - python: "3.9"
            install: full
            deps: pinned
          - python: "3.11"
            install: light
            deps: latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install watex
        run: |
          pip install --upgrade pip 
          if [ -f docs/requirements.txt ]; then pip install -r docs/requirements.txt; fi
          if [[ ${{matrix.install}} == 'full' ]]; then EXTRAS=',pycsamt'; fi
          if [[ ${{matrix.deps }} == 'pinned' ]]; then DEPS='-r ci/deps_pinned.txt'; fi
          pip install .[dev$EXTRAS] $DEPS
      - name: Run tests
        run: make test

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        if: ${{ success() }}

  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install tools
        run: pip install mypy flake8

      - name: Flake8
        run: make lint

      - name: Type checking
        run: make typecheck
